#!/usr/bin/env sh

DIST_DIR_PATH="$PWD/dist";

SERVER_FILE_NAME="server.js";
SERVER_FILE_PATH="$DIST_DIR_PATH/$SERVER_FILE_NAME";

MAKE_SERVER_EXECUTEABLE_COMMAND="chmod +x $SERVER_FILE_PATH";
echo $MAKE_SERVER_EXECUTEABLE_COMMAND;
eval $MAKE_SERVER_EXECUTEABLE_COMMAND;

SERVICE_FILE_NAME="tungenes.service";
SERVICE_FILE_PATH="$DIST_DIR_PATH/$SERVICE_FILE_NAME";

CREATE_SYMLINK_COMMAND="ln -sf $SERVICE_FILE_PATH /etc/systemd/system/$SERVICE_FILE_NAME";
echo $CREATE_SYMLINK_COMMAND;
eval $CREATE_SYMLINK_COMMAND;

RESTART_SYSTEMCTL_COMMAND="systemctl daemon-reload";
echo $RESTART_SYSTEMCTL_COMMAND;
eval $RESTART_SYSTEMCTL_COMMAND;

START_SERVICE_COMMAND="systemctl restart tungenes";
echo $START_SERVICE_COMMAND;
eval $START_SERVICE_COMMAND;

ENABLE_SERVICE_ON_BOOT_COMMAND="systemctl enable tungenes";
echo $ENABLE_SERVICE_ON_BOOT_COMMAND;
eval $ENABLE_SERVICE_ON_BOOT_COMMAND;
